apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue
  name: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  strategy: {}
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}